version: "3.7"
services:
  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.5
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JSON_CONFIG: '{"interactiveLogin":false}'
    hostname: host.docker.internal